### ISSUE TITLE
Recruitment Stats

### ISSUE THREAD

**Issue by drehtisch** [drehtisch/NationStatesAPIBot#25]
### Is your feature request related to a problem? Please describe.
Recruiters should have information about recruitment stats

### Describe the solution you'd like
There should be a command which returns an embedded stating following:
Number of Nations in db in status send, pending, skipped, failed, reserved_manual

Number of Nations in status send who joined the region (with help of dumps?)
Number of Nations in status reserved_manual who joined the region (with help of dumps?)

### Optional (if you have to much time, lol)
Number of Nations Joined* Today 
Number of Nations Joined* Yesterday
Number of Nations Joined* LastWeek
Number of Nations Joined* LastWeek Average per Day
Number of Nations Joined* LastMonth
Number of Nations Joined* LastMonth Average per Day
*and Stayed until now (maybe splitted into recruited through api and manual)

### Describe alternatives you've considered
None

### Additional context
None

**Comment by Krypton-Nova** [comment]
The current implementation only accounts for nations which have remained in the region. So when it returns recruitment stats, they will suffer from CTE's and nations which left. To fix that, I'll need to store the stats instead of recalculating them. I'll need to store them for the optionals as well.

So, do I store the recruitment stats in the DB? And if so, how do I go about adding new stuff to the DB?
