### ISSUE TITLE
Add refounded nations to pending

### ISSUE THREAD

**Issue by drehtisch** [drehtisch/NationStatesAPIBot#6]
- Research / Investigate how to do that
- Add them to pending

1. The Task is to investigate how that could be researched.
2. Actually research it
3. Add it to the pending pool by adding it as nation to the database with status pending. (See GetNewNations for Reference)

**Comment by bion33** [comment]
- Method of research: API documentation, mass-telegram FAQ (not applicable due to custom pool), NS forums (Technical)
- Found out that there is no shard for refounded nations yet. [It was mentioned as part of some future overhaul in 2013]( (https://forum.nationstates.net/viewtopic.php?f=15&t=45424&p=14680197&hilit=api+refounded+nation#p14722008)), but has not yet been implemented since.
- [Found out that the newnations shard's data is older than the happenings shard's data.](https://forum.nationstates.net/viewtopic.php?f=15&t=45424&p=25992875&hilit=api+refounded+nations#p25992875)
- Concluded that [this shard](https://www.nationstates.net/cgi-bin/api.cgi?q=happenings;filter=founding&limit=200) is likely to be a better solution to get both new and refounded nations. It is also able to gather more candidates than the newnations shard (up to 200).

**Comment by bion33** [comment]
Implemented in the above pull request.
